-- V0.2.0 Checkin 天气快照 + 地点（关联分析用）

ALTER TABLE "Checkin" ADD COLUMN "weatherTemp" DOUBLE PRECISION;
ALTER TABLE "Checkin" ADD COLUMN "humidity" DOUBLE PRECISION;
ALTER TABLE "Checkin" ADD COLUMN "aqi" INTEGER;
ALTER TABLE "Checkin" ADD COLUMN "lat" DOUBLE PRECISION;
ALTER TABLE "Checkin" ADD COLUMN "lon" DOUBLE PRECISION;
